/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedTransactionsRouteRouteImport } from './routes/_authenticated/transactions/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSessionsRouteRouteImport } from './routes/_authenticated/sessions/route'
import { Route as AuthenticatedSemestersRouteRouteImport } from './routes/_authenticated/semesters/route'
import { Route as AuthenticatedRolesRouteRouteImport } from './routes/_authenticated/roles/route'
import { Route as AuthenticatedReportsRouteRouteImport } from './routes/_authenticated/reports/route'
import { Route as AuthenticatedProgramsRouteRouteImport } from './routes/_authenticated/programs/route'
import { Route as AuthenticatedLabsRouteRouteImport } from './routes/_authenticated/labs/route'
import { Route as AuthenticatedCreditsRouteRouteImport } from './routes/_authenticated/credits/route'
import { Route as AuthenticatedCoursesRouteRouteImport } from './routes/_authenticated/courses/route'
import { Route as AuthenticatedAuditLogsRouteRouteImport } from './routes/_authenticated/audit-logs/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSemestersSemesterIdRouteImport } from './routes/_authenticated/semesters/$semesterId'
import { Route as AuthenticatedProgramsProgramIdRouteImport } from './routes/_authenticated/programs/$programId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses/$courseId'
import { Route as AuthenticatedStudentTransactionsRouteRouteImport } from './routes/_authenticated/student/transactions/route'
import { Route as AuthenticatedStudentProfileRouteRouteImport } from './routes/_authenticated/student/profile/route'
import { Route as AuthenticatedStudentMyLabsRouteRouteImport } from './routes/_authenticated/student/my-labs/route'
import { Route as AuthenticatedStudentLabCatalogueRouteRouteImport } from './routes/_authenticated/student/lab-catalogue/route'
import { Route as AuthenticatedStudentDashboardRouteRouteImport } from './routes/_authenticated/student/dashboard/route'
import { Route as AuthenticatedStudentCreditWalletRouteRouteImport } from './routes/_authenticated/student/credit-wallet/route'
import { Route as AuthenticatedStudentCertificatesRouteRouteImport } from './routes/_authenticated/student/certificates/route'
import { Route as AuthenticatedStudentAcademicProgressRouteRouteImport } from './routes/_authenticated/student/academic-progress/route'
import { Route as AuthenticatedAdminComputeRdpRouteImport } from './routes/_authenticated/admin.compute.rdp'

const AuthenticatedTransactionsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/transactions/',
)()
const AuthenticatedSessionsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/sessions/',
)()
const AuthenticatedSemestersIndexLazyRouteImport = createFileRoute(
  '/_authenticated/semesters/',
)()
const AuthenticatedRolesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/roles/',
)()
const AuthenticatedReportsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/reports/',
)()
const AuthenticatedProgramsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/programs/',
)()
const AuthenticatedLabsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/labs/',
)()
const AuthenticatedCreditsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/credits/',
)()
const AuthenticatedCoursesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/courses/',
)()
const AuthenticatedAuditLogsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/audit-logs/',
)()
const AuthenticatedStudentTransactionsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/student/transactions/',
)()
const AuthenticatedStudentProfileIndexLazyRouteImport = createFileRoute(
  '/_authenticated/student/profile/',
)()
const AuthenticatedStudentMyLabsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/student/my-labs/',
)()
const AuthenticatedStudentLabCatalogueIndexLazyRouteImport = createFileRoute(
  '/_authenticated/student/lab-catalogue/',
)()
const AuthenticatedStudentDashboardIndexLazyRouteImport = createFileRoute(
  '/_authenticated/student/dashboard/',
)()
const AuthenticatedStudentCreditWalletIndexLazyRouteImport = createFileRoute(
  '/_authenticated/student/credit-wallet/',
)()
const AuthenticatedStudentCertificatesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/student/certificates/',
)()
const AuthenticatedStudentAcademicProgressIndexLazyRouteImport =
  createFileRoute('/_authenticated/student/academic-progress/')()

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRouteRoute =
  AuthenticatedTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsRouteRoute =
  AuthenticatedSessionsRouteRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSemestersRouteRoute =
  AuthenticatedSemestersRouteRouteImport.update({
    id: '/semesters',
    path: '/semesters',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesRouteRoute = AuthenticatedRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRouteRoute =
  AuthenticatedReportsRouteRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramsRouteRoute =
  AuthenticatedProgramsRouteRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsRouteRoute = AuthenticatedLabsRouteRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRouteRoute =
  AuthenticatedCreditsRouteRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesRouteRoute =
  AuthenticatedCoursesRouteRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogsRouteRoute =
  AuthenticatedAuditLogsRouteRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsIndexLazyRoute =
  AuthenticatedTransactionsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/transactions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSessionsIndexLazyRoute =
  AuthenticatedSessionsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSessionsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/sessions/index.lazy').then((d) => d.Route),
  )
const AuthenticatedSemestersIndexLazyRoute =
  AuthenticatedSemestersIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSemestersRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/semesters/index.lazy').then((d) => d.Route),
  )
const AuthenticatedRolesIndexLazyRoute =
  AuthenticatedRolesIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRolesRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/roles/index.lazy').then((d) => d.Route),
  )
const AuthenticatedReportsIndexLazyRoute =
  AuthenticatedReportsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/reports/index.lazy').then((d) => d.Route),
  )
const AuthenticatedProgramsIndexLazyRoute =
  AuthenticatedProgramsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProgramsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/programs/index.lazy').then((d) => d.Route),
  )
const AuthenticatedLabsIndexLazyRoute =
  AuthenticatedLabsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLabsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/labs/index.lazy').then((d) => d.Route),
  )
const AuthenticatedCreditsIndexLazyRoute =
  AuthenticatedCreditsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCreditsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/credits/index.lazy').then((d) => d.Route),
  )
const AuthenticatedCoursesIndexLazyRoute =
  AuthenticatedCoursesIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCoursesRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/courses/index.lazy').then((d) => d.Route),
  )
const AuthenticatedAuditLogsIndexLazyRoute =
  AuthenticatedAuditLogsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAuditLogsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/audit-logs/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSemestersSemesterIdRoute =
  AuthenticatedSemestersSemesterIdRouteImport.update({
    id: '/$semesterId',
    path: '/$semesterId',
    getParentRoute: () => AuthenticatedSemestersRouteRoute,
  } as any)
const AuthenticatedProgramsProgramIdRoute =
  AuthenticatedProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => AuthenticatedProgramsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedCoursesRouteRoute,
  } as any)
const AuthenticatedStudentTransactionsRouteRoute =
  AuthenticatedStudentTransactionsRouteRouteImport.update({
    id: '/student/transactions',
    path: '/student/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentProfileRouteRoute =
  AuthenticatedStudentProfileRouteRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentMyLabsRouteRoute =
  AuthenticatedStudentMyLabsRouteRouteImport.update({
    id: '/student/my-labs',
    path: '/student/my-labs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentLabCatalogueRouteRoute =
  AuthenticatedStudentLabCatalogueRouteRouteImport.update({
    id: '/student/lab-catalogue',
    path: '/student/lab-catalogue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRouteRoute =
  AuthenticatedStudentDashboardRouteRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCreditWalletRouteRoute =
  AuthenticatedStudentCreditWalletRouteRouteImport.update({
    id: '/student/credit-wallet',
    path: '/student/credit-wallet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCertificatesRouteRoute =
  AuthenticatedStudentCertificatesRouteRouteImport.update({
    id: '/student/certificates',
    path: '/student/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentAcademicProgressRouteRoute =
  AuthenticatedStudentAcademicProgressRouteRouteImport.update({
    id: '/student/academic-progress',
    path: '/student/academic-progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentTransactionsIndexLazyRoute =
  AuthenticatedStudentTransactionsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentTransactionsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/transactions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentProfileIndexLazyRoute =
  AuthenticatedStudentProfileIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentProfileRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/profile/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentMyLabsIndexLazyRoute =
  AuthenticatedStudentMyLabsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentMyLabsRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/my-labs/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentLabCatalogueIndexLazyRoute =
  AuthenticatedStudentLabCatalogueIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentLabCatalogueRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/lab-catalogue/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentDashboardIndexLazyRoute =
  AuthenticatedStudentDashboardIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentDashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/dashboard/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentCreditWalletIndexLazyRoute =
  AuthenticatedStudentCreditWalletIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentCreditWalletRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/credit-wallet/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentCertificatesIndexLazyRoute =
  AuthenticatedStudentCertificatesIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentCertificatesRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/certificates/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStudentAcademicProgressIndexLazyRoute =
  AuthenticatedStudentAcademicProgressIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentAcademicProgressRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/student/academic-progress/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminComputeRdpRoute =
  AuthenticatedAdminComputeRdpRouteImport.update({
    id: '/admin/compute/rdp',
    path: '/admin/compute/rdp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRouteRouteWithChildren
  '/courses': typeof AuthenticatedCoursesRouteRouteWithChildren
  '/credits': typeof AuthenticatedCreditsRouteRouteWithChildren
  '/labs': typeof AuthenticatedLabsRouteRouteWithChildren
  '/programs': typeof AuthenticatedProgramsRouteRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteRouteWithChildren
  '/roles': typeof AuthenticatedRolesRouteRouteWithChildren
  '/semesters': typeof AuthenticatedSemestersRouteRouteWithChildren
  '/sessions': typeof AuthenticatedSessionsRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/transactions': typeof AuthenticatedTransactionsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/student/academic-progress': typeof AuthenticatedStudentAcademicProgressRouteRouteWithChildren
  '/student/certificates': typeof AuthenticatedStudentCertificatesRouteRouteWithChildren
  '/student/credit-wallet': typeof AuthenticatedStudentCreditWalletRouteRouteWithChildren
  '/student/dashboard': typeof AuthenticatedStudentDashboardRouteRouteWithChildren
  '/student/lab-catalogue': typeof AuthenticatedStudentLabCatalogueRouteRouteWithChildren
  '/student/my-labs': typeof AuthenticatedStudentMyLabsRouteRouteWithChildren
  '/student/profile': typeof AuthenticatedStudentProfileRouteRouteWithChildren
  '/student/transactions': typeof AuthenticatedStudentTransactionsRouteRouteWithChildren
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/semesters/$semesterId': typeof AuthenticatedSemestersSemesterIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/audit-logs/': typeof AuthenticatedAuditLogsIndexLazyRoute
  '/courses/': typeof AuthenticatedCoursesIndexLazyRoute
  '/credits/': typeof AuthenticatedCreditsIndexLazyRoute
  '/labs/': typeof AuthenticatedLabsIndexLazyRoute
  '/programs/': typeof AuthenticatedProgramsIndexLazyRoute
  '/reports/': typeof AuthenticatedReportsIndexLazyRoute
  '/roles/': typeof AuthenticatedRolesIndexLazyRoute
  '/semesters/': typeof AuthenticatedSemestersIndexLazyRoute
  '/sessions/': typeof AuthenticatedSessionsIndexLazyRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexLazyRoute
  '/admin/compute/rdp': typeof AuthenticatedAdminComputeRdpRoute
  '/student/academic-progress/': typeof AuthenticatedStudentAcademicProgressIndexLazyRoute
  '/student/certificates/': typeof AuthenticatedStudentCertificatesIndexLazyRoute
  '/student/credit-wallet/': typeof AuthenticatedStudentCreditWalletIndexLazyRoute
  '/student/dashboard/': typeof AuthenticatedStudentDashboardIndexLazyRoute
  '/student/lab-catalogue/': typeof AuthenticatedStudentLabCatalogueIndexLazyRoute
  '/student/my-labs/': typeof AuthenticatedStudentMyLabsIndexLazyRoute
  '/student/profile/': typeof AuthenticatedStudentProfileIndexLazyRoute
  '/student/transactions/': typeof AuthenticatedStudentTransactionsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/semesters/$semesterId': typeof AuthenticatedSemestersSemesterIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexLazyRoute
  '/courses': typeof AuthenticatedCoursesIndexLazyRoute
  '/credits': typeof AuthenticatedCreditsIndexLazyRoute
  '/labs': typeof AuthenticatedLabsIndexLazyRoute
  '/programs': typeof AuthenticatedProgramsIndexLazyRoute
  '/reports': typeof AuthenticatedReportsIndexLazyRoute
  '/roles': typeof AuthenticatedRolesIndexLazyRoute
  '/semesters': typeof AuthenticatedSemestersIndexLazyRoute
  '/sessions': typeof AuthenticatedSessionsIndexLazyRoute
  '/transactions': typeof AuthenticatedTransactionsIndexLazyRoute
  '/admin/compute/rdp': typeof AuthenticatedAdminComputeRdpRoute
  '/student/academic-progress': typeof AuthenticatedStudentAcademicProgressIndexLazyRoute
  '/student/certificates': typeof AuthenticatedStudentCertificatesIndexLazyRoute
  '/student/credit-wallet': typeof AuthenticatedStudentCreditWalletIndexLazyRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardIndexLazyRoute
  '/student/lab-catalogue': typeof AuthenticatedStudentLabCatalogueIndexLazyRoute
  '/student/my-labs': typeof AuthenticatedStudentMyLabsIndexLazyRoute
  '/student/profile': typeof AuthenticatedStudentProfileIndexLazyRoute
  '/student/transactions': typeof AuthenticatedStudentTransactionsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRouteRouteWithChildren
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteRouteWithChildren
  '/_authenticated/credits': typeof AuthenticatedCreditsRouteRouteWithChildren
  '/_authenticated/labs': typeof AuthenticatedLabsRouteRouteWithChildren
  '/_authenticated/programs': typeof AuthenticatedProgramsRouteRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteRouteWithChildren
  '/_authenticated/roles': typeof AuthenticatedRolesRouteRouteWithChildren
  '/_authenticated/semesters': typeof AuthenticatedSemestersRouteRouteWithChildren
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/student/academic-progress': typeof AuthenticatedStudentAcademicProgressRouteRouteWithChildren
  '/_authenticated/student/certificates': typeof AuthenticatedStudentCertificatesRouteRouteWithChildren
  '/_authenticated/student/credit-wallet': typeof AuthenticatedStudentCreditWalletRouteRouteWithChildren
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRouteRouteWithChildren
  '/_authenticated/student/lab-catalogue': typeof AuthenticatedStudentLabCatalogueRouteRouteWithChildren
  '/_authenticated/student/my-labs': typeof AuthenticatedStudentMyLabsRouteRouteWithChildren
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRouteRouteWithChildren
  '/_authenticated/student/transactions': typeof AuthenticatedStudentTransactionsRouteRouteWithChildren
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/_authenticated/semesters/$semesterId': typeof AuthenticatedSemestersSemesterIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexLazyRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexLazyRoute
  '/_authenticated/credits/': typeof AuthenticatedCreditsIndexLazyRoute
  '/_authenticated/labs/': typeof AuthenticatedLabsIndexLazyRoute
  '/_authenticated/programs/': typeof AuthenticatedProgramsIndexLazyRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexLazyRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexLazyRoute
  '/_authenticated/semesters/': typeof AuthenticatedSemestersIndexLazyRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexLazyRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexLazyRoute
  '/_authenticated/admin/compute/rdp': typeof AuthenticatedAdminComputeRdpRoute
  '/_authenticated/student/academic-progress/': typeof AuthenticatedStudentAcademicProgressIndexLazyRoute
  '/_authenticated/student/certificates/': typeof AuthenticatedStudentCertificatesIndexLazyRoute
  '/_authenticated/student/credit-wallet/': typeof AuthenticatedStudentCreditWalletIndexLazyRoute
  '/_authenticated/student/dashboard/': typeof AuthenticatedStudentDashboardIndexLazyRoute
  '/_authenticated/student/lab-catalogue/': typeof AuthenticatedStudentLabCatalogueIndexLazyRoute
  '/_authenticated/student/my-labs/': typeof AuthenticatedStudentMyLabsIndexLazyRoute
  '/_authenticated/student/profile/': typeof AuthenticatedStudentProfileIndexLazyRoute
  '/_authenticated/student/transactions/': typeof AuthenticatedStudentTransactionsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/courses'
    | '/credits'
    | '/labs'
    | '/programs'
    | '/reports'
    | '/roles'
    | '/semesters'
    | '/sessions'
    | '/settings'
    | '/transactions'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/student/academic-progress'
    | '/student/certificates'
    | '/student/credit-wallet'
    | '/student/dashboard'
    | '/student/lab-catalogue'
    | '/student/my-labs'
    | '/student/profile'
    | '/student/transactions'
    | '/courses/$courseId'
    | '/errors/$error'
    | '/programs/$programId'
    | '/semesters/$semesterId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps/'
    | '/chats/'
    | '/help-center/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/audit-logs/'
    | '/courses/'
    | '/credits/'
    | '/labs/'
    | '/programs/'
    | '/reports/'
    | '/roles/'
    | '/semesters/'
    | '/sessions/'
    | '/transactions/'
    | '/admin/compute/rdp'
    | '/student/academic-progress/'
    | '/student/certificates/'
    | '/student/credit-wallet/'
    | '/student/dashboard/'
    | '/student/lab-catalogue/'
    | '/student/my-labs/'
    | '/student/profile/'
    | '/student/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/courses/$courseId'
    | '/errors/$error'
    | '/programs/$programId'
    | '/semesters/$semesterId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/audit-logs'
    | '/courses'
    | '/credits'
    | '/labs'
    | '/programs'
    | '/reports'
    | '/roles'
    | '/semesters'
    | '/sessions'
    | '/transactions'
    | '/admin/compute/rdp'
    | '/student/academic-progress'
    | '/student/certificates'
    | '/student/credit-wallet'
    | '/student/dashboard'
    | '/student/lab-catalogue'
    | '/student/my-labs'
    | '/student/profile'
    | '/student/transactions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/audit-logs'
    | '/_authenticated/courses'
    | '/_authenticated/credits'
    | '/_authenticated/labs'
    | '/_authenticated/programs'
    | '/_authenticated/reports'
    | '/_authenticated/roles'
    | '/_authenticated/semesters'
    | '/_authenticated/sessions'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/student/academic-progress'
    | '/_authenticated/student/certificates'
    | '/_authenticated/student/credit-wallet'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/lab-catalogue'
    | '/_authenticated/student/my-labs'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/transactions'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/programs/$programId'
    | '/_authenticated/semesters/$semesterId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/courses/'
    | '/_authenticated/credits/'
    | '/_authenticated/labs/'
    | '/_authenticated/programs/'
    | '/_authenticated/reports/'
    | '/_authenticated/roles/'
    | '/_authenticated/semesters/'
    | '/_authenticated/sessions/'
    | '/_authenticated/transactions/'
    | '/_authenticated/admin/compute/rdp'
    | '/_authenticated/student/academic-progress/'
    | '/_authenticated/student/certificates/'
    | '/_authenticated/student/credit-wallet/'
    | '/_authenticated/student/dashboard/'
    | '/_authenticated/student/lab-catalogue/'
    | '/_authenticated/student/my-labs/'
    | '/_authenticated/student/profile/'
    | '/_authenticated/student/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/semesters': {
      id: '/_authenticated/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof AuthenticatedSemestersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programs': {
      id: '/_authenticated/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedProgramsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs': {
      id: '/_authenticated/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof AuthenticatedLabsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedTransactionsRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedSessionsRouteRoute
    }
    '/_authenticated/semesters/': {
      id: '/_authenticated/semesters/'
      path: '/'
      fullPath: '/semesters/'
      preLoaderRoute: typeof AuthenticatedSemestersIndexLazyRouteImport
      parentRoute: typeof AuthenticatedSemestersRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRolesRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/programs/': {
      id: '/_authenticated/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof AuthenticatedProgramsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedProgramsRouteRoute
    }
    '/_authenticated/labs/': {
      id: '/_authenticated/labs/'
      path: '/'
      fullPath: '/labs/'
      preLoaderRoute: typeof AuthenticatedLabsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedLabsRouteRoute
    }
    '/_authenticated/credits/': {
      id: '/_authenticated/credits/'
      path: '/'
      fullPath: '/credits/'
      preLoaderRoute: typeof AuthenticatedCreditsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedCreditsRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedCoursesRouteRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedAuditLogsRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/semesters/$semesterId': {
      id: '/_authenticated/semesters/$semesterId'
      path: '/$semesterId'
      fullPath: '/semesters/$semesterId'
      preLoaderRoute: typeof AuthenticatedSemestersSemesterIdRouteImport
      parentRoute: typeof AuthenticatedSemestersRouteRoute
    }
    '/_authenticated/programs/$programId': {
      id: '/_authenticated/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof AuthenticatedProgramsProgramIdRouteImport
      parentRoute: typeof AuthenticatedProgramsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRouteRoute
    }
    '/_authenticated/student/transactions': {
      id: '/_authenticated/student/transactions'
      path: '/student/transactions'
      fullPath: '/student/transactions'
      preLoaderRoute: typeof AuthenticatedStudentTransactionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/my-labs': {
      id: '/_authenticated/student/my-labs'
      path: '/student/my-labs'
      fullPath: '/student/my-labs'
      preLoaderRoute: typeof AuthenticatedStudentMyLabsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/lab-catalogue': {
      id: '/_authenticated/student/lab-catalogue'
      path: '/student/lab-catalogue'
      fullPath: '/student/lab-catalogue'
      preLoaderRoute: typeof AuthenticatedStudentLabCatalogueRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/credit-wallet': {
      id: '/_authenticated/student/credit-wallet'
      path: '/student/credit-wallet'
      fullPath: '/student/credit-wallet'
      preLoaderRoute: typeof AuthenticatedStudentCreditWalletRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/certificates': {
      id: '/_authenticated/student/certificates'
      path: '/student/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof AuthenticatedStudentCertificatesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/academic-progress': {
      id: '/_authenticated/student/academic-progress'
      path: '/student/academic-progress'
      fullPath: '/student/academic-progress'
      preLoaderRoute: typeof AuthenticatedStudentAcademicProgressRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/transactions/': {
      id: '/_authenticated/student/transactions/'
      path: '/'
      fullPath: '/student/transactions/'
      preLoaderRoute: typeof AuthenticatedStudentTransactionsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStudentTransactionsRouteRoute
    }
    '/_authenticated/student/profile/': {
      id: '/_authenticated/student/profile/'
      path: '/'
      fullPath: '/student/profile/'
      preLoaderRoute: typeof AuthenticatedStudentProfileIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStudentProfileRouteRoute
    }
    '/_authenticated/student/my-labs/': {
      id: '/_authenticated/student/my-labs/'
      path: '/'
      fullPath: '/student/my-labs/'
      preLoaderRoute: typeof AuthenticatedStudentMyLabsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStudentMyLabsRouteRoute
    }
    '/_authenticated/student/lab-catalogue/': {
      id: '/_authenticated/student/lab-catalogue/'
      path: '/'
      fullPath: '/student/lab-catalogue/'
      preLoaderRoute: typeof AuthenticatedStudentLabCatalogueIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStudentLabCatalogueRouteRoute
    }
    '/_authenticated/student/dashboard/': {
      id: '/_authenticated/student/dashboard/'
      path: '/'
      fullPath: '/student/dashboard/'
      preLoaderRoute: typeof AuthenticatedStudentDashboardIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStudentDashboardRouteRoute
    }
    '/_authenticated/student/credit-wallet/': {
      id: '/_authenticated/student/credit-wallet/'
      path: '/'
      fullPath: '/student/credit-wallet/'
      preLoaderRoute: typeof AuthenticatedStudentCreditWalletIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStudentCreditWalletRouteRoute
    }
    '/_authenticated/student/certificates/': {
      id: '/_authenticated/student/certificates/'
      path: '/'
      fullPath: '/student/certificates/'
      preLoaderRoute: typeof AuthenticatedStudentCertificatesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStudentCertificatesRouteRoute
    }
    '/_authenticated/student/academic-progress/': {
      id: '/_authenticated/student/academic-progress/'
      path: '/'
      fullPath: '/student/academic-progress/'
      preLoaderRoute: typeof AuthenticatedStudentAcademicProgressIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStudentAcademicProgressRouteRoute
    }
    '/_authenticated/admin/compute/rdp': {
      id: '/_authenticated/admin/compute/rdp'
      path: '/admin/compute/rdp'
      fullPath: '/admin/compute/rdp'
      preLoaderRoute: typeof AuthenticatedAdminComputeRdpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAuditLogsRouteRouteChildren {
  AuthenticatedAuditLogsIndexLazyRoute: typeof AuthenticatedAuditLogsIndexLazyRoute
}

const AuthenticatedAuditLogsRouteRouteChildren: AuthenticatedAuditLogsRouteRouteChildren =
  {
    AuthenticatedAuditLogsIndexLazyRoute: AuthenticatedAuditLogsIndexLazyRoute,
  }

const AuthenticatedAuditLogsRouteRouteWithChildren =
  AuthenticatedAuditLogsRouteRoute._addFileChildren(
    AuthenticatedAuditLogsRouteRouteChildren,
  )

interface AuthenticatedCoursesRouteRouteChildren {
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedCoursesIndexLazyRoute: typeof AuthenticatedCoursesIndexLazyRoute
}

const AuthenticatedCoursesRouteRouteChildren: AuthenticatedCoursesRouteRouteChildren =
  {
    AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
    AuthenticatedCoursesIndexLazyRoute: AuthenticatedCoursesIndexLazyRoute,
  }

const AuthenticatedCoursesRouteRouteWithChildren =
  AuthenticatedCoursesRouteRoute._addFileChildren(
    AuthenticatedCoursesRouteRouteChildren,
  )

interface AuthenticatedCreditsRouteRouteChildren {
  AuthenticatedCreditsIndexLazyRoute: typeof AuthenticatedCreditsIndexLazyRoute
}

const AuthenticatedCreditsRouteRouteChildren: AuthenticatedCreditsRouteRouteChildren =
  {
    AuthenticatedCreditsIndexLazyRoute: AuthenticatedCreditsIndexLazyRoute,
  }

const AuthenticatedCreditsRouteRouteWithChildren =
  AuthenticatedCreditsRouteRoute._addFileChildren(
    AuthenticatedCreditsRouteRouteChildren,
  )

interface AuthenticatedLabsRouteRouteChildren {
  AuthenticatedLabsIndexLazyRoute: typeof AuthenticatedLabsIndexLazyRoute
}

const AuthenticatedLabsRouteRouteChildren: AuthenticatedLabsRouteRouteChildren =
  {
    AuthenticatedLabsIndexLazyRoute: AuthenticatedLabsIndexLazyRoute,
  }

const AuthenticatedLabsRouteRouteWithChildren =
  AuthenticatedLabsRouteRoute._addFileChildren(
    AuthenticatedLabsRouteRouteChildren,
  )

interface AuthenticatedProgramsRouteRouteChildren {
  AuthenticatedProgramsProgramIdRoute: typeof AuthenticatedProgramsProgramIdRoute
  AuthenticatedProgramsIndexLazyRoute: typeof AuthenticatedProgramsIndexLazyRoute
}

const AuthenticatedProgramsRouteRouteChildren: AuthenticatedProgramsRouteRouteChildren =
  {
    AuthenticatedProgramsProgramIdRoute: AuthenticatedProgramsProgramIdRoute,
    AuthenticatedProgramsIndexLazyRoute: AuthenticatedProgramsIndexLazyRoute,
  }

const AuthenticatedProgramsRouteRouteWithChildren =
  AuthenticatedProgramsRouteRoute._addFileChildren(
    AuthenticatedProgramsRouteRouteChildren,
  )

interface AuthenticatedReportsRouteRouteChildren {
  AuthenticatedReportsIndexLazyRoute: typeof AuthenticatedReportsIndexLazyRoute
}

const AuthenticatedReportsRouteRouteChildren: AuthenticatedReportsRouteRouteChildren =
  {
    AuthenticatedReportsIndexLazyRoute: AuthenticatedReportsIndexLazyRoute,
  }

const AuthenticatedReportsRouteRouteWithChildren =
  AuthenticatedReportsRouteRoute._addFileChildren(
    AuthenticatedReportsRouteRouteChildren,
  )

interface AuthenticatedRolesRouteRouteChildren {
  AuthenticatedRolesIndexLazyRoute: typeof AuthenticatedRolesIndexLazyRoute
}

const AuthenticatedRolesRouteRouteChildren: AuthenticatedRolesRouteRouteChildren =
  {
    AuthenticatedRolesIndexLazyRoute: AuthenticatedRolesIndexLazyRoute,
  }

const AuthenticatedRolesRouteRouteWithChildren =
  AuthenticatedRolesRouteRoute._addFileChildren(
    AuthenticatedRolesRouteRouteChildren,
  )

interface AuthenticatedSemestersRouteRouteChildren {
  AuthenticatedSemestersSemesterIdRoute: typeof AuthenticatedSemestersSemesterIdRoute
  AuthenticatedSemestersIndexLazyRoute: typeof AuthenticatedSemestersIndexLazyRoute
}

const AuthenticatedSemestersRouteRouteChildren: AuthenticatedSemestersRouteRouteChildren =
  {
    AuthenticatedSemestersSemesterIdRoute:
      AuthenticatedSemestersSemesterIdRoute,
    AuthenticatedSemestersIndexLazyRoute: AuthenticatedSemestersIndexLazyRoute,
  }

const AuthenticatedSemestersRouteRouteWithChildren =
  AuthenticatedSemestersRouteRoute._addFileChildren(
    AuthenticatedSemestersRouteRouteChildren,
  )

interface AuthenticatedSessionsRouteRouteChildren {
  AuthenticatedSessionsIndexLazyRoute: typeof AuthenticatedSessionsIndexLazyRoute
}

const AuthenticatedSessionsRouteRouteChildren: AuthenticatedSessionsRouteRouteChildren =
  {
    AuthenticatedSessionsIndexLazyRoute: AuthenticatedSessionsIndexLazyRoute,
  }

const AuthenticatedSessionsRouteRouteWithChildren =
  AuthenticatedSessionsRouteRoute._addFileChildren(
    AuthenticatedSessionsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedTransactionsRouteRouteChildren {
  AuthenticatedTransactionsIndexLazyRoute: typeof AuthenticatedTransactionsIndexLazyRoute
}

const AuthenticatedTransactionsRouteRouteChildren: AuthenticatedTransactionsRouteRouteChildren =
  {
    AuthenticatedTransactionsIndexLazyRoute:
      AuthenticatedTransactionsIndexLazyRoute,
  }

const AuthenticatedTransactionsRouteRouteWithChildren =
  AuthenticatedTransactionsRouteRoute._addFileChildren(
    AuthenticatedTransactionsRouteRouteChildren,
  )

interface AuthenticatedStudentAcademicProgressRouteRouteChildren {
  AuthenticatedStudentAcademicProgressIndexLazyRoute: typeof AuthenticatedStudentAcademicProgressIndexLazyRoute
}

const AuthenticatedStudentAcademicProgressRouteRouteChildren: AuthenticatedStudentAcademicProgressRouteRouteChildren =
  {
    AuthenticatedStudentAcademicProgressIndexLazyRoute:
      AuthenticatedStudentAcademicProgressIndexLazyRoute,
  }

const AuthenticatedStudentAcademicProgressRouteRouteWithChildren =
  AuthenticatedStudentAcademicProgressRouteRoute._addFileChildren(
    AuthenticatedStudentAcademicProgressRouteRouteChildren,
  )

interface AuthenticatedStudentCertificatesRouteRouteChildren {
  AuthenticatedStudentCertificatesIndexLazyRoute: typeof AuthenticatedStudentCertificatesIndexLazyRoute
}

const AuthenticatedStudentCertificatesRouteRouteChildren: AuthenticatedStudentCertificatesRouteRouteChildren =
  {
    AuthenticatedStudentCertificatesIndexLazyRoute:
      AuthenticatedStudentCertificatesIndexLazyRoute,
  }

const AuthenticatedStudentCertificatesRouteRouteWithChildren =
  AuthenticatedStudentCertificatesRouteRoute._addFileChildren(
    AuthenticatedStudentCertificatesRouteRouteChildren,
  )

interface AuthenticatedStudentCreditWalletRouteRouteChildren {
  AuthenticatedStudentCreditWalletIndexLazyRoute: typeof AuthenticatedStudentCreditWalletIndexLazyRoute
}

const AuthenticatedStudentCreditWalletRouteRouteChildren: AuthenticatedStudentCreditWalletRouteRouteChildren =
  {
    AuthenticatedStudentCreditWalletIndexLazyRoute:
      AuthenticatedStudentCreditWalletIndexLazyRoute,
  }

const AuthenticatedStudentCreditWalletRouteRouteWithChildren =
  AuthenticatedStudentCreditWalletRouteRoute._addFileChildren(
    AuthenticatedStudentCreditWalletRouteRouteChildren,
  )

interface AuthenticatedStudentDashboardRouteRouteChildren {
  AuthenticatedStudentDashboardIndexLazyRoute: typeof AuthenticatedStudentDashboardIndexLazyRoute
}

const AuthenticatedStudentDashboardRouteRouteChildren: AuthenticatedStudentDashboardRouteRouteChildren =
  {
    AuthenticatedStudentDashboardIndexLazyRoute:
      AuthenticatedStudentDashboardIndexLazyRoute,
  }

const AuthenticatedStudentDashboardRouteRouteWithChildren =
  AuthenticatedStudentDashboardRouteRoute._addFileChildren(
    AuthenticatedStudentDashboardRouteRouteChildren,
  )

interface AuthenticatedStudentLabCatalogueRouteRouteChildren {
  AuthenticatedStudentLabCatalogueIndexLazyRoute: typeof AuthenticatedStudentLabCatalogueIndexLazyRoute
}

const AuthenticatedStudentLabCatalogueRouteRouteChildren: AuthenticatedStudentLabCatalogueRouteRouteChildren =
  {
    AuthenticatedStudentLabCatalogueIndexLazyRoute:
      AuthenticatedStudentLabCatalogueIndexLazyRoute,
  }

const AuthenticatedStudentLabCatalogueRouteRouteWithChildren =
  AuthenticatedStudentLabCatalogueRouteRoute._addFileChildren(
    AuthenticatedStudentLabCatalogueRouteRouteChildren,
  )

interface AuthenticatedStudentMyLabsRouteRouteChildren {
  AuthenticatedStudentMyLabsIndexLazyRoute: typeof AuthenticatedStudentMyLabsIndexLazyRoute
}

const AuthenticatedStudentMyLabsRouteRouteChildren: AuthenticatedStudentMyLabsRouteRouteChildren =
  {
    AuthenticatedStudentMyLabsIndexLazyRoute:
      AuthenticatedStudentMyLabsIndexLazyRoute,
  }

const AuthenticatedStudentMyLabsRouteRouteWithChildren =
  AuthenticatedStudentMyLabsRouteRoute._addFileChildren(
    AuthenticatedStudentMyLabsRouteRouteChildren,
  )

interface AuthenticatedStudentProfileRouteRouteChildren {
  AuthenticatedStudentProfileIndexLazyRoute: typeof AuthenticatedStudentProfileIndexLazyRoute
}

const AuthenticatedStudentProfileRouteRouteChildren: AuthenticatedStudentProfileRouteRouteChildren =
  {
    AuthenticatedStudentProfileIndexLazyRoute:
      AuthenticatedStudentProfileIndexLazyRoute,
  }

const AuthenticatedStudentProfileRouteRouteWithChildren =
  AuthenticatedStudentProfileRouteRoute._addFileChildren(
    AuthenticatedStudentProfileRouteRouteChildren,
  )

interface AuthenticatedStudentTransactionsRouteRouteChildren {
  AuthenticatedStudentTransactionsIndexLazyRoute: typeof AuthenticatedStudentTransactionsIndexLazyRoute
}

const AuthenticatedStudentTransactionsRouteRouteChildren: AuthenticatedStudentTransactionsRouteRouteChildren =
  {
    AuthenticatedStudentTransactionsIndexLazyRoute:
      AuthenticatedStudentTransactionsIndexLazyRoute,
  }

const AuthenticatedStudentTransactionsRouteRouteWithChildren =
  AuthenticatedStudentTransactionsRouteRoute._addFileChildren(
    AuthenticatedStudentTransactionsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditLogsRouteRoute: typeof AuthenticatedAuditLogsRouteRouteWithChildren
  AuthenticatedCoursesRouteRoute: typeof AuthenticatedCoursesRouteRouteWithChildren
  AuthenticatedCreditsRouteRoute: typeof AuthenticatedCreditsRouteRouteWithChildren
  AuthenticatedLabsRouteRoute: typeof AuthenticatedLabsRouteRouteWithChildren
  AuthenticatedProgramsRouteRoute: typeof AuthenticatedProgramsRouteRouteWithChildren
  AuthenticatedReportsRouteRoute: typeof AuthenticatedReportsRouteRouteWithChildren
  AuthenticatedRolesRouteRoute: typeof AuthenticatedRolesRouteRouteWithChildren
  AuthenticatedSemestersRouteRoute: typeof AuthenticatedSemestersRouteRouteWithChildren
  AuthenticatedSessionsRouteRoute: typeof AuthenticatedSessionsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedTransactionsRouteRoute: typeof AuthenticatedTransactionsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStudentAcademicProgressRouteRoute: typeof AuthenticatedStudentAcademicProgressRouteRouteWithChildren
  AuthenticatedStudentCertificatesRouteRoute: typeof AuthenticatedStudentCertificatesRouteRouteWithChildren
  AuthenticatedStudentCreditWalletRouteRoute: typeof AuthenticatedStudentCreditWalletRouteRouteWithChildren
  AuthenticatedStudentDashboardRouteRoute: typeof AuthenticatedStudentDashboardRouteRouteWithChildren
  AuthenticatedStudentLabCatalogueRouteRoute: typeof AuthenticatedStudentLabCatalogueRouteRouteWithChildren
  AuthenticatedStudentMyLabsRouteRoute: typeof AuthenticatedStudentMyLabsRouteRouteWithChildren
  AuthenticatedStudentProfileRouteRoute: typeof AuthenticatedStudentProfileRouteRouteWithChildren
  AuthenticatedStudentTransactionsRouteRoute: typeof AuthenticatedStudentTransactionsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAdminComputeRdpRoute: typeof AuthenticatedAdminComputeRdpRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditLogsRouteRoute:
    AuthenticatedAuditLogsRouteRouteWithChildren,
  AuthenticatedCoursesRouteRoute: AuthenticatedCoursesRouteRouteWithChildren,
  AuthenticatedCreditsRouteRoute: AuthenticatedCreditsRouteRouteWithChildren,
  AuthenticatedLabsRouteRoute: AuthenticatedLabsRouteRouteWithChildren,
  AuthenticatedProgramsRouteRoute: AuthenticatedProgramsRouteRouteWithChildren,
  AuthenticatedReportsRouteRoute: AuthenticatedReportsRouteRouteWithChildren,
  AuthenticatedRolesRouteRoute: AuthenticatedRolesRouteRouteWithChildren,
  AuthenticatedSemestersRouteRoute:
    AuthenticatedSemestersRouteRouteWithChildren,
  AuthenticatedSessionsRouteRoute: AuthenticatedSessionsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedTransactionsRouteRoute:
    AuthenticatedTransactionsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStudentAcademicProgressRouteRoute:
    AuthenticatedStudentAcademicProgressRouteRouteWithChildren,
  AuthenticatedStudentCertificatesRouteRoute:
    AuthenticatedStudentCertificatesRouteRouteWithChildren,
  AuthenticatedStudentCreditWalletRouteRoute:
    AuthenticatedStudentCreditWalletRouteRouteWithChildren,
  AuthenticatedStudentDashboardRouteRoute:
    AuthenticatedStudentDashboardRouteRouteWithChildren,
  AuthenticatedStudentLabCatalogueRouteRoute:
    AuthenticatedStudentLabCatalogueRouteRouteWithChildren,
  AuthenticatedStudentMyLabsRouteRoute:
    AuthenticatedStudentMyLabsRouteRouteWithChildren,
  AuthenticatedStudentProfileRouteRoute:
    AuthenticatedStudentProfileRouteRouteWithChildren,
  AuthenticatedStudentTransactionsRouteRoute:
    AuthenticatedStudentTransactionsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAdminComputeRdpRoute: AuthenticatedAdminComputeRdpRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
