export const LAB_PORTS = {
  JUPYTER: 8888,
  WEB_LAB: 8080,
};

export const LABS = [
  {
    id: "python-lab",
    title: "Python Programming Lab",
    subtitle: "Master Python Basics to Advanced",
    semester: "Semester 1",
    logo: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png",
    rating: 4.9,
    reviewCount: 210,
    durationMinutes: 90,
    credits: 30,
    complexity: "Beginner",
    category: "Programming",
    description: "Browser-based IDE with Python 3.11 — syntax, data structures, and algorithms without local PyCharm install.",
    status: "ready",
    taskDefinition: "vlab-dev-python-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: {
        enabled: true,
        port: LAB_PORTS.WEB_LAB,
      },
    },
  },
  {
    id: "java-lab",
    title: "Java Development Lab",
    subtitle: "Object-Oriented Programming",
    semester: "Semester 1",
    logo: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png",
    rating: 4.7,
    reviewCount: 155,
    durationMinutes: 120,
    credits: 40,
    complexity: "Intermediate",
    category: "Programming",
    description: "Browser IDE with JDK 21 — write, compile, and run Java without Eclipse or local install.",
    status: "ready",
    taskDefinition: "vlab-dev-java-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
  {
    id: "linux-lab",
    title: "Linux Administration Lab",
    subtitle: "Bash Scripting & SysAdmin",
    semester: "Semester 2",
    logo: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png",
    rating: 4.8,
    reviewCount: 180,
    durationMinutes: 60,
    credits: 25,
    complexity: "Beginner",
    category: "SysAdmin",
    description: "Ubuntu shell with gcc, gdb, and make — commands, scripting, and C debugging in the browser.",
    status: "ready",
    taskDefinition: "vlab-dev-linux-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
  {
    id: "dbms-lab",
    title: "DBMS & SQL Lab",
    subtitle: "Database Management Systems",
    semester: "Semester 2",
    logo: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/sql/sql.png",
    rating: 4.6,
    reviewCount: 120,
    durationMinutes: 75,
    credits: 35,
    complexity: "Intermediate",
    category: "Databases",
    description: "Oracle XE 21c, MySQL, and PostgreSQL — SQL queries and database design in one container.",
    status: "ready",
    taskDefinition: "vlab-dev-dbms-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
  {
    id: "data-science-lab",
    title: "Data Science-I",
    subtitle: "Analysis & Visualization",
    semester: "Semester 3",
    logo: "https://cdn-icons-png.freepik.com/512/4824/4824797.png",
    rating: 4.9,
    reviewCount: 95,
    durationMinutes: 120,
    credits: 50,
    complexity: "Advanced",
    category: "Programming",
    description: "Jupyter Notebook with Python 3.11 (pandas, scikit-learn, seaborn). RStudio/Anaconda available if syllabus mandates R.",
    status: "ready",
    taskDefinition: "vlab-dev-datascience-task",
    runtime: {
      type: "jupyter",
      port: LAB_PORTS.JUPYTER,
      path: "/lab/tree/lab.ipynb",
      containerApi: { enabled: true, port: LAB_PORTS.JUPYTER },
    },
  },
  {
    id: "big-data-lab",
    title: "Big Data Analytics-I",
    subtitle: "Large Scale Data Processing",
    semester: "Semester 3",
    logo: "https://www.vhv.rs/dpng/d/500-5004244_transparent-big-data-icon-png-big-data-and.png",
    rating: 4.7,
    reviewCount: 60,
    durationMinutes: 150,
    credits: 60,
    complexity: "Advanced",
    category: "Databases",
    description: "Hadoop 3.3, Maven, and JDK 21 — MapReduce and HDFS labs via browser IDE (Hadoop 2.7 on request).",
    status: "ready",
    taskDefinition: "vlab-dev-bigdata-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
  {
    id: "testing-lab",
    title: "Software Testing Automation",
    subtitle: "QA & Selenium Testing",
    semester: "Semester 4",
    logo: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png",
    rating: 4.5,
    reviewCount: 45,
    durationMinutes: 90,
    credits: 35,
    complexity: "Intermediate",
    category: "Programming",
    description: "Selenium WebDriver with Chrome, ChromeDriver, Python, and JDK 17 — programmatic test automation (not Selenium IDE extension).",
    status: "ready",
    taskDefinition: "vlab-dev-testing-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
  {
    id: "agile-lab",
    title: "Agile Methodology",
    subtitle: "Scrum & Project Management",
    semester: "Semester 3",
    logo: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png",
    rating: 4.8,
    reviewCount: 110,
    durationMinutes: 60,
    credits: 20,
    complexity: "Beginner",
    category: "SysAdmin",
    description: "Agile frameworks with Java programming exercises.",
    status: "ready",
    taskDefinition: "vlab-dev-agilemethodology-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
  {
    id: "mobile-app-lab",
    title: "Fundamental of Mobile Application",
    subtitle: "Android SDK & Gradle",
    semester: "Semester 4",
    logo: "https://images.icon-icons.com/2108/PNG/512/flutter_icon_130936.png",
    rating: 4.6,
    reviewCount: 80,
    durationMinutes: 120,
    credits: 45,
    complexity: "Intermediate",
    category: "Programming",
    description: "Android command-line SDK, Gradle, and JDK 17 — build Android projects in the browser (CLI workflow; no Android Studio GUI/emulator on cloud).",
    status: "ready",
    taskDefinition: "vlab-dev-android-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
  {
    id: "dotnet-lab",
    title: "Web Technology Using .NET",
    subtitle: "ASP.NET Core Development",
    semester: "Semester 3",
    logo: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/csharp/csharp.png",
    rating: 4.7,
    reviewCount: 55,
    durationMinutes: 100,
    credits: 40,
    complexity: "Intermediate",
    category: "Programming",
    description: "code-server (VS Code in browser) with .NET SDK 8 — C# and ASP.NET Core without Visual Studio install.",
    status: "ready",
    taskDefinition: "vlab-dev-dotnet-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
  {
    id: "software-eng-lab",
    title: "Software Engineering",
    subtitle: "SDLC & Architecture",
    semester: "Semester 4",
    logo: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/visual-studio-code/visual-studio-code.png",
    rating: 4.8,
    reviewCount: 130,
    durationMinutes: 90,
    credits: 30,
    complexity: "Intermediate",
    category: "Programming",
    description: "code-server, PlantUML, and Draw.io — SDLC diagrams, UML, and architecture patterns in the browser.",
    status: "ready",
    taskDefinition: "vlab-dev-softwareengeering-task",
    runtime: {
      type: "ide",
      port: LAB_PORTS.WEB_LAB,
      path: "/",
      containerApi: { enabled: true, port: LAB_PORTS.WEB_LAB },
    },
  },
];

export const SUB_LABS = {
  "Python Programming Lab": [
    { id: "s1", title: "Variables & Types", duration: "15m", difficulty: "Beginner" },
    { id: "s2", title: "Control Flow", duration: "25m", difficulty: "Beginner" },
  ],
  "Java Development Lab": [
    { id: "s3", title: "Classes & Objects", duration: "30m", difficulty: "Intermediate" },
  ],
};

export const getLabById = (labId) => LABS.find((lab) => lab.id === labId);
